services:
  mongodb:
    image: mongo:7.0
    container_name: crypto_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - crypto_net

  data_collector:
    build:
      context: .
      dockerfile: Dockerfile.data_collector
    container_name: crypto_data_collector
    depends_on:
      - mongodb
    networks:
      - crypto_net

volumes:
  mongo_data:

networks:
  crypto_net:
    name: crypto_network
