name: Build Workflow

on:
  push:
    branches: ['**']  # Run on every push to any branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-id: ${{ steps.set-build-id.outputs.build-id }}
    steps:
      - name: Set build ID
        id: set-build-id
        run: echo "build-id=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          docker --version

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/docker-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile*') }}

      - name: Build and tag images
        run: |
          # Build FastAPI image
          docker build \
            --cache-from=type=local,src=/tmp/docker-cache \
            --tag crypto_fastapi:${{ steps.set-build-id.outputs.build-id }} \
            --file src/api_user/docker/Dockerfile.fastapi \
            .
          
          # Build Dash image
          docker build \
            --tag crypto_dash:${{ steps.set-build-id.outputs.build-id }} \
            --file src/api_user/docker/Dockerfile.dash \
            .
          
          # Build Data Collector image
          docker build \
            --tag crypto_data_collector:${{ steps.set-build-id.outputs.build-id }} \
            --file src/collection_admin/docker/Dockerfile.data_collector \
            .
      
      - name: Save build ID
        run: echo "${{ steps.set-build-id.outputs.build-id }}" > build_id.txt
      
      - name: Upload build ID
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build_id.txt
          retention-days: 1

