name: CI - Feature Branch Workflow

on:
  push:
    branches-ignore:
      - 'master'   # run this workflow on all other branches

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml