name: CI - Feature Branch Workflow

on:
  push:
    branches: ['master']  # run only on master branch. Change to ignore master branch

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml