name: CI - Feature Branch Workflow

on:
  push:
    branches-ignore:
      - 'master'   # run this workflow on all other branches

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run linter
      run: |
        flake8 src tests

  test:
    runs-on: ubuntu-latest
    # needs: lint  # Only run if lint succeeds
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest tests/
  
  build:
    runs-on: ubuntu-latest
    # needs: [lint, test]  # Only run if both pass

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker --version

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/docker-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile*') }}

      - name: Build FastAPI image
        run: |
          docker build \
            --cache-from=type=local,src=/tmp/docker-cache \
            --tag my-app-fastapi:ci-build \
            --file src/api_user/docker/Dockerfile.fastapi \
            --progress=plain \
            .

      - name: Build Dash image
        run: |
          docker build \
            --cache-from=type=local,src=/tmp/docker-cache \
            --tag my-app-dash:ci-build \
            --file src/api_user/docker/Dockerfile.dash \
            --progress=plain \
            .

      - name: Build Data Collector image
        run: |
          docker build \
            --cache-from=type=local,src=/tmp/docker-cache \
            --tag data-collector:ci-build \
            --file src/collection_admin/docker/Dockerfile.data_collector \
            --progress=plain \
            .