name: Release Workflow

on:
  push:
    branches: ['**']  # Run on any branch for testing

jobs:
  # First run the build and test workflow
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml

  # Then run the release steps
  release:
    needs: build-and-test
    runs-on: ubuntu-latest
    env:
      BUILD_ID: ${{ needs.build-and-test.outputs.build-id }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and Push FastAPI Image
        run: |
          docker pull crypto_fastapi:${{ env.BUILD_ID }}
          docker tag crypto_fastapi:${{ env.BUILD_ID }} ${{ secrets.DOCKERHUB_USERNAME }}/crypto_fastapi:latest
          docker tag crypto_fastapi:${{ env.BUILD_ID }} ${{ secrets.DOCKERHUB_USERNAME }}/crypto_fastapi:${{ github.sha }}
          docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/crypto_fastapi

      - name: Tag and Push Dash Image
        run: |
          docker pull crypto_dash:${{ env.BUILD_ID }}
          docker tag crypto_dash:${{ env.BUILD_ID }} ${{ secrets.DOCKERHUB_USERNAME }}/crypto_dash:latest
          docker tag crypto_dash:${{ env.BUILD_ID }} ${{ secrets.DOCKERHUB_USERNAME }}/crypto_dash:${{ github.sha }}
          docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/crypto_dash

      - name: Tag and Push Data Collector Image
        run: |
          docker pull crypto_data_collector:${{ env.BUILD_ID }}
          docker tag crypto_data_collector:${{ env.BUILD_ID }} ${{ secrets.DOCKERHUB_USERNAME }}/crypto_data_collector:latest
          docker tag crypto_data_collector:${{ env.BUILD_ID }} ${{ secrets.DOCKERHUB_USERNAME }}/crypto_data_collector:${{ github.sha }}
          docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/crypto_data_collector
